# -*- coding: utf-8 -*-
"""Webscraping Wikipedia Table using Beautiful Soup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zxLy56rh5ottd-ADmUIWwBxNT3SlJF4w
"""

# install BeautifulSoup
!pip install BeautifulSoup4

# install requests
!pip install requests

# import scraping libraries
from bs4 import BeautifulSoup #library to parse HTML documents
import requests #library to handle requests

# import required libraries
import pandas as pd #library for data analysis
import numpy as np

#get the response in the form of HTML
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'}
table_class = 'wikitable sortable jquery - tablesorter'
url = "https://en.wikipedia.org/wiki/List_of_online_payment_service_providers"
r = requests.get(url, headers=headers)

#parse data from the html into a Beautifulsoup object
soup = BeautifulSoup(r.content, "html.parser")
indiatable = soup.find('table',{'class':'wikitable'})

#Convert Wikipedia Table into a python dataframe
df = pd.read_html(str(indiatable))
#convert list to dataframe
df = pd.DataFrame(df[0])
df